// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG9Hf7gWvswq9ETsH8FQtZ7f7xZmc1k2Y',
    appId: '1:355718108204:web:c232cf7462d200ae4cad89',
    messagingSenderId: '355718108204',
    projectId: 'assignment-3d0e8',
    authDomain: 'assignment-3d0e8.firebaseapp.com',
    storageBucket: 'assignment-3d0e8.appspot.com',
    measurementId: 'G-GJQS5RSZTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgP7FybsUx7jGWDAfkChsRb3sj1n0t1yM',
    appId: '1:355718108204:android:fc150dd35d323a944cad89',
    messagingSenderId: '355718108204',
    projectId: 'assignment-3d0e8',
    storageBucket: 'assignment-3d0e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz0eNyk8QbSbLJk0BY0ZT4Y_TQWLzETeQ',
    appId: '1:355718108204:ios:cd469b90a146d6834cad89',
    messagingSenderId: '355718108204',
    projectId: 'assignment-3d0e8',
    storageBucket: 'assignment-3d0e8.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz0eNyk8QbSbLJk0BY0ZT4Y_TQWLzETeQ',
    appId: '1:355718108204:ios:43d43f868e7624064cad89',
    messagingSenderId: '355718108204',
    projectId: 'assignment-3d0e8',
    storageBucket: 'assignment-3d0e8.appspot.com',
    iosBundleId: 'com.example.assignment.RunnerTests',
  );
}
