// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBokhlkyaT0fLm9f2uEtQEQNjppmp2jRSo',
    appId: '1:993216801040:web:482adf55018669cbb59d95',
    messagingSenderId: '993216801040',
    projectId: 'assignment-a56c8',
    authDomain: 'assignment-a56c8.firebaseapp.com',
    storageBucket: 'assignment-a56c8.appspot.com',
    measurementId: 'G-NDZ2Y8TCTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaLeZfnYTcHxmj3o-tb7WyLBWy_3sa7FI',
    appId: '1:993216801040:android:d02945a6b357c04eb59d95',
    messagingSenderId: '993216801040',
    projectId: 'assignment-a56c8',
    storageBucket: 'assignment-a56c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJKLl1kXbqvwxQEBYHDXZ955BaRJNGBTc',
    appId: '1:993216801040:ios:946877404f26dce1b59d95',
    messagingSenderId: '993216801040',
    projectId: 'assignment-a56c8',
    storageBucket: 'assignment-a56c8.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJKLl1kXbqvwxQEBYHDXZ955BaRJNGBTc',
    appId: '1:993216801040:ios:bcf9f5046db6dc22b59d95',
    messagingSenderId: '993216801040',
    projectId: 'assignment-a56c8',
    storageBucket: 'assignment-a56c8.appspot.com',
    iosBundleId: 'com.example.assignment.RunnerTests',
  );
}
